# fly.toml file generated for howhotistheshop on 2023-05-27T09:34:14-04:00

app = "howhotistheshop"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
[mounts]
  source = "howhotdata"
  destination = "/data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443