[tool.poetry]
name = "howhotistheshop"
version = "0.1.0"
description = "Tell my wife how hot her shop is wherever she is"
authors = ["Matt Bachmann <bachmann.matt@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.pylint.master]
min-similarity-lines = 11
ignore-docstrings = "yes"
ignore-comments = "yes"
ignore-imports = "yes"

[tool.pylint.'MESSAGES CONTROL']
disable = "C0114, C0116, C0115"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
jinja2 = "^3.0.1"
flask = "^2.0.1"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"
coverage = "^5.5"
isort = "^5.9.2"
mypy = "^0.910"
pylint = "^2.9.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
